# Welcome to Jekyll!

# Website settings
title: "CA Coach"
description: "CA Coach, Coaching Center"
keywords: "CA,Coach,Coaching,Institute,Accounts,Learning,Destination,Law,Maths,Economics"

baseurl: "/"
url: "https://cacoach.github.io/"
# url: "http://127.0.0.1:4000"

# blog img path
# img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'CA Coach'
  first_name: 'CA'
  last_name: 'Coach'
  email: 'cacoach@outlook.in'
  # facebook_username: 'Mangalutsav'
  # github_username: 'Mangalutsav'
  # head_img: 'static/img/landing/Utsav.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Subjects'
  projects: 'Project'
  contact: 'Contact'

# my projects
project:
  SigIntChecker:
    name: 'Ankit Babbar'
    # url: '/Mangalutsav/Check_SIGINT'
    img: 'static/img/landing/person.png'
  Stroom:
    name: 'Sampurna Narula'
    # url: '/Hareshkh/Stroom'
    img: 'static/img/landing/person.png'
  Youtoo:
    name: 'Youtoo'
    # url: '/Mangalutsav/Youtoo'
    img: 'static/img/landing/person.png'
  Yolog:
    name: 'Yolog'
    # url: '/Karandesai-96/Yolog'
    img: 'static/img/landing/person.png'

# blog index
index:
  home: 'Home'
  # python: 'Python'
  # linux: 'Linux'
  # JS: 'JS'
  # database: 'Database'
  # life: 'Life'

# comment
# disqus:
#   name: Kraken
#   public_key: FTvHZuuS0XcH4XZHNWzASYpEPQ2VHnGrtk7NRPNKMpKnjZaSaRDmVImMZ4HLsPnF

# google analytics
ga:
  id: UA-77166641-2

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
fb_admins:          http://facebook.com/mangalutsav
fb_appid:           1758376257751682
